/* #1 */
WITH THREE_MONTH_SUM AS
         (SELECT MANAGER_ID,
                 SALE_DATE,
                 SALE_AMOUNT,
                 MANAGER_FIRST_NAME,
                 MANAGER_LAST_NAME,
                 SUM(SALE_AMOUNT) OVER (
                     PARTITION BY MANAGER_ID
                     ORDER BY SALE_DATE RANGE BETWEEN INTERVAL '3' MONTH PRECEDING AND
                     INTERVAL '0' MONTH FOLLOWING
                     ) AS SUM_BY_THREE_MONTHS
          FROM V_FACT_SALE
          WHERE SALE_DATE BETWEEN TO_DATE('2013-11-01', 'YYYY-MM-DD') AND TO_DATE('2014-12-31', 'YYYY-MM-DD')
         )
SELECT
    DISTINCT MANAGER_ID,
             MANAGER_FIRST_NAME,
             MANAGER_LAST_NAME,
             TO_CHAR(SALE_DATE, 'MM') AS MONTH,
             (SUM_BY_THREE_MONTHS*0.05) AS BONUS
FROM THREE_MONTH_SUM
WHERE SUM_BY_THREE_MONTHS IN (
    SELECT MAX(SUM_BY_THREE_MONTHS) OVER (
        PARTITION BY TO_CHAR(SALE_DATE, 'YYYY-MM')
        ORDER BY SALE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS MAX_BY_MONTH
    FROM THREE_MONTH_SUM
    WHERE SALE_DATE BETWEEN TO_DATE('2014-01-01', 'YYYY-MM-DD') AND TO_DATE('2014-12-31', 'YYYY-MM-DD')
)
ORDER BY MONTH;
